name: DockerHub

on:
  push:
    branches:
      - master
      - dev
      - stable
    tags:
      - 'v*.*.*'

jobs:
  multiarch-build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
        
      - name: Get Docker tags
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: jrcs/letsencrypt-nginx-proxy-companion
          tag-semver: |
            {{version}}
            {{major}}.{{minor}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Retrieve version
        run: echo "GIT_DESCRIBE=$(git describe --tags)" >> $GITHUB_ENV
      
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          build-args: GIT_DESCRIBE=${{ env.GIT_DESCRIBE }} 
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: |
            ${{ github.ref != 'refs/heads/master' && steps.docker_meta.outputs.tags || '' }}
            ${{ github.ref == 'refs/heads/master' && 'jrcs/letsencrypt-nginx-proxy-companion:latest' || '' }}
          labels: ${{ steps.docker_meta.outputs.labels }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
